name = "DiefAlpha Pack Adventure"
author = "DieAlpha"
version = "2026"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de8459b52f6d71e9cc7cf21795b04637735d18446f3e86b42216954a36dc9267"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
