name = "DiefAlpha Pack"
author = "DieAlpha"
version = "2026"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b87b4bc76ff28b062ecb7a7805044e5ced6c82a0e4cbb617b7fd81e0bdfab009"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
