name = "DiefAlpha Pack"
author = "DieAlpha"
version = "2026"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb0d7206de9fd6b4b04f50b99414ae8cdf861eeaf3a3079a88371a14ffd52e9c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
